export const SET_ACTIVE_USER_ID = "SET_ACTIVE_USER_ID";
export const SET_TYPING_VALUE = "SET_TYPING_VALUE";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SET_FILTER_VALUE = "SET_FILTER_VALUE";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
